- name: ssh into Ec2 and run shell commands
  hosts: ubuntu
  become: yes
  gather_facts: True
  tasks:
  - name: update ec2
    shell: sudo apt update && sudo apt upgrade -y
  - name: search for openjdk
    shell: sudo apt search openjdk
  - name: download openjdk11
    shell: sudo apt install openjdk-11-jdk -y
  - name: curl for jenkins
    shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \ /usr/share/keyrings/jenkins-keyring.asc > /dev/null  
  - name: echo variable
    shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \ https://pkg.jenkins.io/debian-stable binary/ | sudo tee \ /etc/apt/sources.list.d/jenkins.list > /dev/null  
  - name: update jenkins pkg
    shell: sudo apt-get update
  - name: Install a list of packages
    shell: sudo apt-get install jenkins -y

- name: ssh into Ec2 and install openjdk
  hosts: ubuntu1
  become: yes
  gather_facts: True
  tasks:
  - name: update ec2
    shell: sudo apt update && sudo apt upgrade -y
  - name: search for openjdk
    shell: sudo apt search openjdk
  - name: download openjdk11
    shell: sudo apt install openjdk-11-jdk -y

- name: ssh into Ec2 and install docker
  hosts: ubuntu2
  become: yes
  gather_facts: True
  tasks:
  - name: update ec2
    shell: sudo apt update && sudo apt upgrade -y
  - name: search for openjdk
    shell: sudo apt search openjdk
  - name: download openjdk11
    shell: sudo apt install openjdk-11-jdk -y
  - name: install needed modules
    shell: sudo apt-get install \ ca-certificates \ curl \ gnupg \ lsb-release
  - name: add dockers key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dea>  - name: update docker package
    shell: sudo apt-get update && apt-get upgrade -y
  - name: install docker engine
    shell: echo \ "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \ $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - name: chmod 
    shell: sudo chmod 666 /var/run/docker.sock
